name: remote ssh command
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: 
            'python3 /root/tips_script/wechat_push.py'
